apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-example
  namespace: echons
  
plugin: key-auth
config:
  key_names:
  - apikey
  # anonymous: alex # WIth this is  works completely anonimous