# apiVersion: networking.istio.io/v1beta1
# kind: ServiceEntry
# metadata:
#   name: my-service-entry
#   namespace: echons
# spec:
#   hosts:
#   - echo2  # Fully qualified domain name (FQDN) of the Service
#   ports:
#   - number: 1027
#     name: http
#     protocol: HTTP
#   resolution: STATIC  # Use STATIC resolution for ClusterIP
#   location: MESH_INTERNAL  # Treat the Service as part of the mesh
#   endpoints:
#   - address: 10.98.105.135 # ClusterIP of the Service
#     ports:
#       http: 1027
# ---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: echons
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: key-auth-example
spec:
  parentRefs:
  - name: kong-gw-echo
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo-httproute
    backendRefs:
    # - name: echo
    #   kind: Service
    #   port: 1027
    #   weight: 60
    - name: echo2
      kind: Service
      port: 1027
      # weight: 40
