apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-tls
  namespace: echons
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: key-auth-example
spec:
  ingressClassName: kong
  # tls:
  #   - hosts:
  #     - localhost
  #     secretName: my-tls-secret
  rules:
  - http:
      paths:
      - path: /echo-ingress
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo
            port:
              number: 1027
# Works without the Gateway and Gateway Class - its not using them
