{{- range $name, $httproutes := .Values.httpRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    {{- toYaml $.Values.metadata.labels | nindent 4 }}
  annotations:
    {{- toYaml $.Values.metadata.annotations | nindent 4 }}
spec:
  hostnames:
    {{- toYaml .hostnames | nindent 4 }}
  rules:
    {{- toYaml .rules | nindent 4 }}
---
{{- end }}